[devnet]
name = "devnet"
stacks_node_rpc_address = "http://localhost:20443"
stacks_node_rpc_port = 20443
stacks_node_p2p_port = 20444
bitcoin_node_rpc_address = "localhost"
bitcoin_node_rpc_port = 18443
bitcoin_node_rpc_username = "devnet"
bitcoin_node_rpc_password = "devnet"
bitcoin_node_p2p_port = 18444
miner_mnemonic = "twice kind fence tip hidden twist action slim paint position trophy feed"
miner_address = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
deployment_fee_rate = 1
