[project]
name = "chainlink-pay"
authors = ["ChainLinkPay Team"]
license = "MIT"
description = "ChainLinkPay - AI-powered Bitcoin payment platform"

[project.requirements]
clarinet = "^1.0.0"

[contracts.enhanced-payment]
path = "contracts/enhanced-payment.clar"
depends_on = []
