[network]
name = "devnet"
stacks_node_rpc_address = "http://localhost:20443"
stacks_node_p2p_address = "http://localhost:20444"
stacks_node_event_address = "http://localhost:3700"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "your_mnemonic_here"
balance = 1000000000000

[accounts.wallet_1]
mnemonic = "your_mnemonic_here"
balance = 1000000000000

[accounts.wallet_2]
mnemonic = "your_mnemonic_here"
balance = 1000000000000
