[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
stacks_node_p2p_address = "https://api.testnet.hiro.so"
stacks_node_event_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "your_mnemonic_here"
balance = 1000000000000

[accounts.wallet_1]
mnemonic = "your_mnemonic_here"
balance = 1000000000000

[accounts.wallet_2]
mnemonic = "your_mnemonic_here"
balance = 1000000000000
